### ISSUE TITLE
No viene el Post

### ISSUE THREAD

**Issue by nicopuri** [KCHETO/api#12]
@acrosa Anoche encontre un bug medio raro. Cree un nuevo post con la imagen, todo funcionaba perfecto. Pero cuando di una opinion (like o dislike) me dejo de venir el post en:
- Post del Profile (```/posts/me```)
- En el detalle de una ```Notification``` no me viene el Post asociado.

Puede ser que por haber dado un Like se borre la referencia al resto de los objetos?

**Comment by acrosa** [comment]
@nicopuri cuando mandas el etag si no los datos no cambiaron la respuesta es nada y 204 NO CONTENT, esto es porque cuesta mucho armar el response y estaría bueno que las apps puedan llamar notifications endpoint frecuentemente.
