### ISSUE TITLE
User info en el Post

### ISSUE THREAD

**Issue by nicopuri** [KCHETO/api#2]
Necesito que en ```Post``` me vengan los siguientes 4 datos. Algo asi:

```
user: {
    id: {id},
    photo_url: {photo_url},
    nickname: {nickname},
    name: {name}
}
```

**Comment by acrosa** [comment]
confírmame que esto te anda OK ahora, a ver si se puede cerrar el issue.

**Comment by nicopuri** [comment]
El nickname sigue sin llegar.

**Comment by acrosa** [comment]
@nicopuri ahora?
